<?php
$SET_THEMYSQLHOSTNAME="localhost";$SET_THEMYSQLUSERNAME="root";$SET_THEMYSQLPASSWORD="root";$SET_THEMYSQLDBNAME="test";$SET_THEMYSQLLOGINTABLE="setuptest";
$SET_COOKIEEXPIRY=9;$SET_THEMULTIPLELOGIN=0;?>